name: example
description: A sample of mint usage
version: 1.0.0

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  au: ^0.1.0
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: '^2.1.11'
  lints: ^2.0.0
  test: ^1.16.0
  json_serializable: ^6.3.1
  mint: ^0.2.0
