name: au
description: Annotation for mint, a code generation framework.
repository: https://github.com/nullbtb/mint
version: 0.2.1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.16.0

dev_dependencies:
  test: ^1.0.0