name: mint
description: Code generation framework
version: 0.1.0
publish_to: none

environment:  
  sdk: '>=2.17.0 <3.0.0'

dependencies:  
  build: '^2.3.0'  
  source_gen: ^1.2.2
  mustache_template: '^2.0.0'
  analyzer: ^5.1.0
  au: ^0.1.0  
  json_annotation: ^4.7.0
  json_serializable: ^6.3.1

dev_dependencies:  
  build_test: 
  build_config: ^1.0.0
  build_runner: '^2.1.11'
  source_gen_test: ^1.0.4
  test: ^1.21.6
