name: mint
description: Code generation framework with support for copyWith, copyJar, equality, and JsonSerializable (fromJson, toJson).
repository: https://github.com/nullbtb/mint
version: 0.3.1

environment:  
  sdk: '>=2.17.0 <3.0.0'

dependencies:  
  build: '^2.3.0'  
  source_gen: ^1.2.2
  mustache_template: '^2.0.0'
  analyzer: ^5.1.0
  au: ^0.1.0
  json_annotation: ^4.7.0
  json_serializable: ^6.3.1
  glob: ^2.0.0
  path: ^1.8.0

dev_dependencies:  
  build_test: 
  build_config: ^1.0.0
  build_runner: '^2.1.11'
  source_gen_test: ^1.0.4
  test: ^1.21.6
